# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build 'SimpleApi\SimpleApi.Core\SimpleApi.Core.csproj' --configuration $(buildConfiguration)
- script: dotnet build 'SimpleApi\SimpleApi.Infrastructure\SimpleApi.Infrastructure.csproj' --configuration $(buildConfiguration)
- script: dotnet build 'SimpleApi\SimpleApi.Api\SimpleApi.Api.csproj' --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'