# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: |
      SimpleApi\SimpleApi.Core\SimpleApi.Core.csproj
      SimpleApi\SimpleApi.Infrastructure\SimpleApi.Infrastructure.csproj
      SimpleApi\SimpleApi.Api\SimpleApi.Api.csproj
      SimpleApi\SimpleApi.UnitTests\SimpleApi.UnitTests.csproj
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**